### ISSUE TITLE
Erro na linha 53

### ISSUE THREAD

**Issue by ramirezemerick88** [MartinsMessias/iphone_amazon-web-crawler#1]
self.worksheet.write(f'A{index}', product_title, self.normal)
                                   ^
SyntaxError: invalid syntax

**Comment by ramirezemerick88** [comment]
python3 amazon_spider.py 
  File "amazon_spider.py", line 53
    self.worksheet.write(f'A{index}', product_title, self.normal)
                                   ^
SyntaxError: invalid syntax

**Comment by MartinsMessias** [comment]
Thank you for opening this issue. However, I have to tell you that this is the correct syntax as you can see here.
[https://xlsxwriter.readthedocs.io/worksheet.html](https://xlsxwriter.readthedocs.io/worksheet.html)

Here are some examples:

The write() method supports two forms of notation to designate the position of cells: Row-column notation and A1 notation:

# These are equivalent.
worksheet.write(0, 0, 'Hello')
worksheet.write('A1', 'Hello')

Verify if you are using ```scrapy runspider amazon_spider.py``` to run.

😄 Have a nice day.
